name: Checkout another private repo

on:
  workflow_dispatch:

jobs:
  private-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo code
        uses: actions/checkout@v4

      - name: Checkout Private Repo code
        uses: actions/checkout@v4
        with:
          repository: dmays/private-test-repo
          ref: main
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

