name: How do secrets and vars do

on:
  workflow_dispatch:

jobs:
  prove:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    env:
      REPO_SECRET: ${{ secrets.REPO_SECRET }}
      REPO_VAR: ${{ vars.REPO_VAR }}
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      ENV_VAR: ${{ vars.ENV_VAR }}

    steps:
      - uses: actions/checkout@v4

      - name: Output Vars
        run: |
          echo "REPO_VAR: <$REPO_VAR>"
          echo "REPO_SECRET: <$REPO_SECRET>"
          echo "ENV_VAR: <$ENV_VAR>"
          echo "ENV_SECRET: <$ENV_SECRET>"
